#!/bin/bash

export cflags="-ggdb3 -O0 -march=native -pipe"
export cxxflags="${cflags}"
export buildtype=debug
export builddir=${MESA_SRCDIR:-$(git rev-parse --show-toplevel)}/build-debug

exec mesa-run "$@"
