#!/bin/bash

export cflags="-ggdb3 -O2 -march=native -fno-omit-frame-pointer -pipe"
export cxxflags="${cflags}"
export buildtype=debugoptimized
export builddir=${MESA_SRCDIR:-$(git rev-parse --show-toplevel)}/build-debug-optimized

exec mesa-run "$@"
