#!/bin/bash

die() {
	echo "$1"
	exit 255
}

[[ -z ${builddir} ]] && die "builddir must be set"
prefix="${builddir}"/install

machine=$(uname -m)
case "$machine" in
x86_64)
	vulkan_drivers=intel
	gallium_drivers=iris
	tools=drm-shim,intel
	extra_args+=(
		-Dintel-clc=enabled
		-Dintel-rt=enabled
	)
	;;
aarch64|arm*)
	vulkan_drivers=freedreno
	gallium_drivers=freedreno
	tools=drm-shim,freedreno
	;;
esac

case "$1" in
wipe|wipeout)
	echo "Removing ${builddir}"
	rm -r "${builddir}"
	;&
configure)
	export LLVM_MAJOR_VERSION="19"
	export LLVM_CONFIG="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/llvm-config"
	#export CC="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/clang"
	#export CXX="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/clang++"
	#export CC_LD="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/lld"
	#export CXX_LD="${CC_LD}"
	export CC_LD="mold"
	export CXX_LD="mold"

	args=(
		--pkg-config-path "/usr/lib/llvm/${LLVM_MAJOR_VERSION}/lib64/pkgconfig"
		-Dprefix="${prefix}"
		-Dc_args="${cflags}"
		-Dcpp_args="${cxxflags}"
		-Dtools="${tools}"
		-Dbuild-tests=false
		-Dvulkan-drivers="${vulkan_drivers}"
		-Dgallium-drivers="${gallium_drivers}"
		-Dgallium-rusticl=false
		-Dgallium-va=auto
		-Dgallium-xa=disabled
		-Dvideo-codecs="vc1dec,h264dec,h264enc,h265dec,h265enc"
		-Dvulkan-beta=true
		-Dbuildtype="${buildtype}"
		-Dbackend=ninja
		"${extra_args[@]}"
		"${builddir}"
	)
	echo meson setup --reconfigure "${args[@]}"
	exec meson setup --reconfigure "${args[@]}"
	;;
build)
	exec nj "${buildtype}" install
	;;
esac

LD_PRELOAD="${GCC_ASAN_PRELOAD}" exec meson devenv -C "${builddir}" -w "${PWD}" "$@"
