#!/bin/bash

die() {
	echo "$1"
	exit 255
}

[[ -z ${builddir} ]] && die "builddir must be set"
prefix="${builddir}"/install

IFS=: read -r -a extra_args <<< "${extra_args}"

machine=$(uname -m)
case "$machine" in
x86_64)
	vulkan_drivers=intel
	gallium_drivers=iris
	tools=drm-shim,intel
	extra_args+=(
		-Dintel-rt=disabled
	)
	;;
aarch64|arm*)
	vulkan_drivers=freedreno
	gallium_drivers=freedreno
	tools=drm-shim,freedreno
	;;
esac

case "$1" in
wipe|wipeout)
	echo "Removing ${builddir}"
	rm -r "${builddir}"
	;&
configure)
	export LLVM_MAJOR_VERSION="19"
	llvm_config_paths=(
		"/usr/bin/llvm-config-${LLVM_MAJOR_VERSION}"
		"/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/llvm-config"
	)
	for llvm_config in "${llvm_config_paths[@]}"; do
		if [[ -x "${llvm_config}" ]]; then
			export LLVM_CONFIG="${llvm_config}"
			break
		fi
	done

	llvm_pkg_config_paths=(
		"/usr/lib/llvm/${LLVM_MAJOR_VERSION}/lib64/pkgconfig"
		"/usr/lib/x86_64-linux-gnu/pkgconfig"
	)
	for llvm_pkg_config_path in "${llvm_pkg_config_paths[@]}"; do
		if [[ -f "${llvm_pkg_config_path}/LLVMSPIRVLib.pc" ]]; then
			export LLVM_CONFIG="${llvm_config}"
			spirv_llvm_translator_pkg_config_path="${llvm_pkg_config_path}"
			break
		fi
	done

	#export CC="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/clang"
	#export CXX="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/clang++"
	#export CC_LD="/usr/lib/llvm/${LLVM_MAJOR_VERSION}/bin/lld"
	#export CXX_LD="${CC_LD}"
	export CC_LD="mold"
	export CXX_LD="mold"

	args=(
		--pkg-config-path "${spirv_llvm_translator_pkg_config_path}"
		-Dprefix="${prefix}"
		-Dc_args="${cflags}"
		-Dcpp_args="${cxxflags}"
		-Dtools="${tools}"
		-Dbuild-tests=false
		-Dvulkan-drivers="${vulkan_drivers}"
		-Dgallium-drivers="${gallium_drivers}"
		-Dgallium-rusticl=false
		-Dgallium-va=disabled
		-Dintel-elk=false
		-Dvulkan-beta=true
		-Dbuildtype="${buildtype}"
		-Dbackend=ninja
		"${extra_args[@]}"
		"${builddir}"
	)
	echo meson setup --reconfigure "${args[@]}"
	exec meson setup --reconfigure "${args[@]}"
	;;
build)
	exec nj "${buildtype}" install
	;;
esac

LD_PRELOAD="${GCC_ASAN_PRELOAD}" exec meson devenv -C "${builddir}" -w "${PWD}" "$@"
