#!/bin/bash

export cflags="-O2 -march=native -fno-omit-frame-pointer -pipe"
export cxxflags="${cflags}"
export buildtype=release
export builddir=${MESA_SRCDIR:-~/projects/mesa}/build-release

exec mesa-run "$@"
